applications/empleados/urls.py
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListaAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'lista-by-area/<shorname>', 
        views.ListaByAreaEmpleados.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados_admin', 
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('lista-by-job/<job>', views.ListaByJobEmpleados.as_view()),
    path('buscar-emplado/', views.ListaEmpleadosbyKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccesView.as_view(), 
        name='correcto'
    ), 
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado'
    ), 
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(), 
        name='eliminar_empleado'
    ), 
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleados/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField


# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleados'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad 

class Empleado(models.Model):
    # Modelo para tabla empleado

    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'DEVOPS'),
        ('4', 'OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombre completo',
        max_length= 60,
        blank=True,
    )
    job = models.CharField('Job', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    habilidades = models.ManyToManyField(Habilidades)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True) 
    # hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Lista empleados'
        verbose_name_plural = 'Empleados activos'
        ordering = ['first_name', 'last_name']
        unique_together = ('first_name', 'departamento') 
 

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name
    

applications/empleados/forms.py
from django import forms

from. models import Empleado

class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/empleados/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)

# models
from .models import Empleado

# forms
from .forms import EmpleadoForm

# Create your views here.
class InicioView(TemplateView):
    ''' Vista que carga la página de inicio '''
    template_name = 'inicio.html'


# 1) Lista todos los empleados de la empresa
class ListaAllEmpleados(ListView):
    template_name = 'empleados/list_all.html'
    paginate_by = 7 
    ordering = 'first_name'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )  
        return lista
    

class ListaEmpleadosAdmin(ListView):
    template_name = 'empleados/lista_empleados.html'
    paginate_by = 7 
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado
    


# 2) Listar todos los empleados que pertenecen a un área de la empresa
class ListaByAreaEmpleados(ListView):
    template_name = 'empleados/list_by_area.html'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name = area
        ) 
        return lista
    

# 3) Listar empleados por trabajo
class ListaByJobEmpleados(ListView):
    template_name = 'empleados/list_by_job.html'
    
    def get_queryset(self):
        job = self.kwargs['job']
        lista = Empleado.objects.filter(
            job = job
        ) 
        return lista
       

# 4) listar los empleados por palabra clave
class ListaEmpleadosbyKword(ListView):
    template_name = 'empleados/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('*' * 20 )
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )  
        return lista


# 5) Listar habilidades de un empleado 
class ListHabilidadesEmpleado(ListView):
    template_name = 'empleados/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=8)
        return empleado.habilidades.all()
    

# Detail View 
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "empleados/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        # todo el proceso para verificar empleado del mes
        context['titulo'] = 'Empleado del mes'
        return context


# Create View 
class EmpleadoCreateView(CreateView):
    template_name = "empleados/add.html"
    model = Empleado 
    form_class = EmpleadoForm
    success_url = reverse_lazy('empleados_app:empleados_admin')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        print(empleado)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name 
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)

class SuccesView(TemplateView):
    template_name = "empleados/success.html"  


# Update View
class EmpleadoUpdateView(UpdateView):
    template_name = "empleados/update.html"
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
     ]
    success_url = reverse_lazy('empleados_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('**************************METODO POST*****************')
        print('===================================')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        print('**************************METODO from_valid*****************')
        print('******************************************************')
        return super(EmpleadoUpdateView, self).form_valid(form)
    

# Delete View 
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "empleados/delete.html"
    success_url = reverse_lazy('empleados_app:empleados_all')

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = reverse_lazy('empleados_app:correcto')
        self.object.delete()
        return super().post(request, *args, **kwargs)

templates/empleados/add.html
{% extends 'base.html' %}

{% block title %}
    Registrar Empleado
{% endblock title %}

{% block content %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
            <div class="medium-6 cell">
              <label>Nombre: 
                {{ form.first_name }}
              </label>
            </div>
            <div class="medium-6 cell">
              <label>Apellido:
                {{ form.last_name }}
              </label>
            </div>
            <div class="medium-6 cell">
              <label>Trabajo:
                {{ form.job }}
              </label>
            </div>
            <div class="medium-6 cell">
              <label>Departamento:
                {{ form.departamento }}
              </label>
            </div>
            <div class="medium-12 cell">
              <label>Habilidades:
                {{ form.habilidades }}
              </label>
            </div>
            <div class="medium-12 cell">
              <label>Foto:
                {{ form.avatar }}
              </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
    



 

templates/empleados/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>


<h3>Lista resultados</h3>
<ul>
    
    {% for e in empleados %}
        <li>{{ e }}</li>
    {% endfor %}
        
</ul>

templates/empleados/delete.html
{% extends 'base.html' %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{ object.full_name }}</h1> 
        
        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout alert">
              <h5>¿Desea eliminar este empleado?</h5>
              <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
    
    

templates/empleados/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ object.full_name }}
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" >
        <div class="cell large-4 card" style="width: 300px; margin-top: 100px;">
          <div class="card-divider">
            {{ empleado.get_job_display }}
          </div>
          
          {% if empleado.avatar %}
            <img src="{{ empleado.avatar.url }}">
          {% else %}
            <img src="{% static 'img/default_avatar.png' %}" >
          {% endif %}
            
          <div class="card-section">
            <h4>{{ empleado.full_name }}</h4>
            <p>{{ empleado.last_name }}</p>
            <p>{{ empleado.departamento.shor_name }}</p>
            <p><span class="label">Habilidades:</span></p>
            <ul class="vertical menu">
                
                {% for habilidad in empleado.habilidades.all %}
                    <li>{{ habilidad.habilidad }}</li>
                {% endfor %}
                    
            </ul>
          </div>
        </div>
    </div>
</div>
    
{% endblock content %}
    
    

<h1>Detalle de un empleado {{ titulo }}</h1>

{{ empleado }}

<h3>Todos los datos:</h3>

<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.job }}</p>
<p>{{ empleado.departamneto }}</p>
<p>{{ empleado.habilidades }}</p>
<p>{{ empleado.hoja_vida }}</p>

templates/empleados/habilidades.html
<h1>Habilidades del empleado</h1>

<ul>

    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
        
</ul>

templates/empleados/list_all.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/header.html' %}
 
<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Lista empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
          <table>
            <thead>
              <tr>
                <th width="200">ID</th>
                <th>NOMBRES</th>
                <th width="150">APELLIDOS</th>
                <th width="150">DEPARTAMENTO</th>
                <th width="150">ACCION</th>
              </tr>
            </thead>
            <tbody>
              {% for e in empleados %}  
              <tr>
                <td>{{ e.id }}</td>
                <td>{{ e.first_name }}</td>
                <td>{{ e.last_name }}</td>
                <td>{{ e.departamento }}</td>
                <td><a class="button warning" href="{% url 'empleados_app:empleado_detail' e.id %}">Ver</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
              <ul class="pagination">
                
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li> 
                {% endif %}
                
                {% for pagina in paginator.page_range%}
       
                {% if page_obj.number == pagina %} 
                <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                {% else %}
                <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                {% endif %}                  
                {% endfor %}
                 
                
                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% endif %}
                  
              </ul>   
            </nav>
            {% endif %}
                
        </div>
    </div>    
</div>

{% endblock content %}
    

templates/empleados/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    Lista empleados por departamwnto
{% endblock title %}
   

{% block content %}
    {% include 'includes/header.html' %} 

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area: </div>
            <div class="cell">
                <div class="cell">
                  <table>
                      <thead>
                        <tr>
                          <th width="200">ID</th>
                          <th>NOMBRES</th>
                          <th width="150">APELLIDOS</th>
                          <th width="150">DEPARTAMENTO</th>
                          <th width="150">ACCION</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for e in empleados %}  
                        <tr>
                          <td>{{ e.id }}</td>
                          <td>{{ e.first_name }}</td>
                          <td>{{ e.last_name }}</td>
                          <td>{{ e.departamento }}</td>
                          <td><a class="button warning" href="{% url 'empleados_app:empleado_detail' e.id %}">Ver</a></td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
    

<h1>Lista empleados por departamento</h1>


<ul>

    {% for e in object_list %}
        <li>{{ e }}</li>
    {% endfor %}

</ul>

templates/empleados/list_by_job.html
<h1>Lista empleados por Trabajo</h1>


<ul>

    {% for e in object_list %}
        <li>{{ e }}</li>
    {% endfor %}

</ul>

templates/empleados/lista_empleados.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/header.html' %}
 
<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Lista empleados</h1>
        <div class="cell">
          <table>
            <thead>
              <tr>
                <th width="200">ID</th>
                <th>NOMBRES</th>
                <th width="150">APELLIDOS</th>
                <th width="150">DEPARTAMENTO</th>
                <th width="150">ACCION</th>
              </tr>
            </thead>
            <tbody>
              {% for e in empleados %}  
              <tr>
                <td>{{ e.id }}</td>
                <td>{{ e.first_name }}</td>
                <td>{{ e.last_name }}</td>
                <td>{{ e.departamento }}</td>
                <td>
                    <a class="button success" href="{% url 'empleados_app:modificar_empleado' e.id %}">Editar</a> 
                </td>
                <td>
                    <a class="button alert" href="{% url 'empleados_app:eliminar_empleado' e.id %}">Eliminar</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
              <ul class="pagination">
                
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li> 
                {% endif %}
                
                {% for pagina in paginator.page_range%}
       
                {% if page_obj.number == pagina %} 
                <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                {% else %}
                <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                {% endif %}                  
                {% endfor %}
                 
                
                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% endif %}
                  
              </ul>   
            </nav>
            {% endif %}
                
        </div>
    </div>    
</div>

{% endblock content %}
    

templates/empleados/success.html
<h1>Felicitaciones, se guardo correctamente el empleado</h1>

templates/empleados/update.html
{% extends 'base.html' %}


{% block title %}
    Editar Empleado
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">  
            <form class="grid-x grid-margin-x" method="POST"> {% csrf_token %}
                  <div class="large-6 cell">
                    <label>Nombres:
                      {{ form.first_name }}
                    </label>
                  </div>
                  <div class="large-6 cell">
                    <label>Apellidos:
                      {{ form.last_name }}
                    </label>
                  </div>
                  <div class="large-6 cell">
                    <label>Trabajo
                      {{ form.job }}
                    </label>
                  </div>
                  <div class="large-6 cell">
                    <label>Area
                      {{ form.departamento }}
                    </label>
                  </div>
                  <div class="large-6 cell">
                    <label>Habilidades extra:
                      {{ form.habilidades }}
                    </label>
                  </div>
                  <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                  </div>
            </form>
        </div>
    </div>
</div>
    
{% endblock content %}
    
    