applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'departamento_app'

urlpatterns = [
    path(
        'DepartamentoListView/', 
        views.DepartamentoListView.as_view(), 
        name='departamento_list'
    ),
    path('new-department/', views.NewDepartmentView.as_view(), name='nuevo_departamento'),
]

applications/empleados/urls.py
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListaAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'lista-by-area/<shorname>', 
        views.ListaByAreaEmpleados.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados_admin', 
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('lista-by-job/<job>', views.ListaByJobEmpleados.as_view()),
    path('buscar-emplado/', views.ListaEmpleadosbyKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccesView.as_view(), 
        name='correcto'
    ), 
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado'
    ), 
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(), 
        name='eliminar_empleado'
    ), 
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'empleados_app:empleados_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a></li>
        <li><a href="{% url 'empleados_app:empleados_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a href="{% url 'empleados_app:empleado_add' %}" type="button" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>