applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'departamento_app'

urlpatterns = [
    path(
        'DepartamentoListView/', 
        views.DepartamentoListView.as_view(), 
        name='departamento_list'
    ),
    path('new-department/', views.NewDepartmentView.as_view(), name='nuevo_departamento'),
]

applications/empleados/urls.py
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListaAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'lista-by-area/<shorname>', 
        views.ListaByAreaEmpleados.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados_admin', 
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('lista-by-job/<job>', views.ListaByJobEmpleados.as_view()),
    path('buscar-emplado/', views.ListaEmpleadosbyKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccesView.as_view(), 
        name='correcto'
    ), 
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado'
    ), 
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(), 
        name='eliminar_empleado'
    ), 
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return str(self.id) + ' - ' + self.name + ' - ' + self.shor_name
    

applications/departamento/forms.py
from django import forms 

# class NewDepartmentForm(forms.Form):
#     nombre = forms.CharField(max_length=50)
#     apellido = forms.CharField(max_length=50)
#     departamento = forms.CharField(max_length=50)
#     shorname = forms.CharField(max_length=20)


class NewDepartmentForm(forms.Form):
    nombre = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Nombre del empleado'})
    )
    apellido = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Apellido del empleado'})
    )
    departamento = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Nombre del departamento'})
    )
    shorname = forms.CharField(
        max_length=20,
        widget=forms.TextInput(attrs={'placeholder': 'Short name del departamento'})
    )
 

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView

from applications.empleados.models import Empleado
from .models import Departamento 
from .forms import NewDepartmentForm


class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = 'departamentos'


class NewDepartmentView(FormView):
    template_name = 'departamento/new_department.html'
    form_class = NewDepartmentForm
    success_url = '/'
    
    def form_valid(self, form):
        print('*****************Estamos en el form valid*******************')

        depa = Departamento(
            name=form.cleaned_data['departamento'], 
            shor_name=form.cleaned_data['shorname'], 
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )
        return super(NewDepartmentView, self).form_valid(form)
    

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
    Lista departamentos
{% endblock title %}



{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>                        
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shor_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'empleados_app:empleados_area' departamento.shor_name %}">Ver Empleados</a>
                            </td>
                        </tr>                            
                        {% endfor %}                            
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/departamento/new_department.html
{% extends 'base.html' %}


{% block title %}
    Registrar Departamento
{% endblock title %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
              <label>Nombres:
                {{ form.nombre }}
              </label>
            </div>
            <div class="medium-6 cell">
              <label>Apellidos:
                {{ form.apellido }}
              </label>
            </div>
            <div class="medium-6 cell">
              <label>Departamento:
                {{ form.departamento }}
              </label>
            </div>
            <div class="medium-6 cell">
              <label>Nombre Corto:
                {{ form.shorname }}
              </label>
            </div>
        </form>
    </div>
</div>
    
{% endblock content %}
    


<h1>Registrar nuevo Departamento</h1>

<form method="POST"> {% csrf_token %}
    <h3>Datos Empleados</h3>
    <p>
        {{ form.nombre }}
    </p>
    <p>
        {{ form.apellido }}
    </p>
    <h3>Datos de Departamento</h3>
    <p>
        {{ form.departamento }}
    </p>
    <p>
        {{ form.shorname }}
    </p>
    <button type="submit">Guardar</button>
</form>